version: '3.7'

services:
  nginx:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/www
      - ./config/production/nginx.conf:/etc/nginx/nginx.conf
      - ./config/production/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - nest

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/

  nest:
    build:
      dockerfile: ./Nest.production.dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
