version: '3.7'

services:
  server:
    build: .
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./:/www
      - ./config/hosts:/ets/hosts

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432