version: '3.7'

services:
  nginx:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/www
      - ./config/production/nginx.conf:/etc/nginx/nginx.conf
      - ./config/production/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./nginx/public_html:/public_html
      - ./config/production/dhparam:/etc/nginx/dhparam
      - ./nginx/certbot/conf:/etc/nginx/ssl
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - nest

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email yanrus09@gmail.com --agree-tos --no-eff-email -d yaniddze.com
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/logs:/var/log/letsencrypt
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt

  nest:
    build:
      dockerfile: ./Nest.production.dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
