name: Deploy
on:
  push:
    branches:
      - master

jobs:
  Rebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Deploy Node.Js
        uses: appleboy/ssh-actions@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          password: ${{secrets.SSH_PASS}}
          username: ${{secrets.SSH_USER}}

          script: |
            cd gta5-helper-server
            npm ci
            npx webpack
            docker-compose -f docker-compose.production.yaml build
            docker-compose -f docker-compose.production.yaml down
            docker-compose -f docker-compose.production.yaml up -d
