name: Deploy
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  Rebuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /root/gta5-helper-server
    permissions: read-all|write-all
    steps:
      - run: npm ci
      - run: npm run build
      - run: docker-compose -f docker-compose.production.yml build
      - run: docker-compose -f docker-compose.production.yml down
      - run: docker-compose -f docker-compose.production.yml up -d
